//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailworksDownloader.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RailworksDownloader.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available packages were already downloaded..
        /// </summary>
        public static string AllDownDesc {
            get {
                return ResourceManager.GetString("AllDownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package is already installed..
        /// </summary>
        public static string AlreadyInstalFail {
            get {
                return ResourceManager.GetString("AlreadyInstalFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will be restarted.
        /// </summary>
        public static string ApplicationRestart {
            get {
                return ResourceManager.GetString("ApplicationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download packages.
        /// </summary>
        public static string CantDownload {
            get {
                return ResourceManager.GetString("CantDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam DLC.
        /// </summary>
        public static string CatDLC {
            get {
                return ResourceManager.GetString("CatDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string CatEnv {
            get {
                return ResourceManager.GetString("CatEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotives.
        /// </summary>
        public static string CatLoco {
            get {
                return ResourceManager.GetString("CatLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other/Uncategorised.
        /// </summary>
        public static string CatOther {
            get {
                return ResourceManager.GetString("CatOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railvehicle dependencies.
        /// </summary>
        public static string CatRVDep {
            get {
                return ResourceManager.GetString("CatRVDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery.
        /// </summary>
        public static string CatScenery {
            get {
                return ResourceManager.GetString("CatScenery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM PACKAGE.
        /// </summary>
        public static string CatSystem {
            get {
                return ResourceManager.GetString("CatSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track objects.
        /// </summary>
        public static string CatTrackObj {
            get {
                return ResourceManager.GetString("CatTrackObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagons.
        /// </summary>
        public static string CatWag {
            get {
                return ResourceManager.GetString("CatWag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking installed DLCs.
        /// </summary>
        public static string CheckingDLC {
            get {
                return ResourceManager.GetString("CheckingDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ColorHintBlue {
            get {
                return ResourceManager.GetString("ColorHintBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string ColorHintGreen {
            get {
                return ResourceManager.GetString("ColorHintGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing in scenario.
        /// </summary>
        public static string ColorHintPurple {
            get {
                return ResourceManager.GetString("ColorHintPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string ColorHintRed {
            get {
                return ResourceManager.GetString("ColorHintRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string ColorHintYellow {
            get {
                return ResourceManager.GetString("ColorHintYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following package seems to be controlled by DLS but not installed through this app:.
        /// </summary>
        public static string ConflictFileDesc1 {
            get {
                return ResourceManager.GetString("ConflictFileDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please decide how to continue!.
        /// </summary>
        public static string ConflictFileDesc2 {
            get {
                return ResourceManager.GetString("ConflictFileDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict file found!.
        /// </summary>
        public static string ConflictFileTitle {
            get {
                return ResourceManager.GetString("ConflictFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non specified.
        /// </summary>
        public static string CountryNon {
            get {
                return ResourceManager.GetString("CountryNon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while counting size of file {0}!.
        /// </summary>
        public static string CountSizeFail {
            get {
                return ResourceManager.GetString("CountSizeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when crawling route &quot;{0}&quot;!.
        /// </summary>
        public static string CrawlingRouteFail {
            get {
                return ResourceManager.GetString("CrawlingRouteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error!.
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files used from package {0} in route {1}:.
        /// </summary>
        public static string DepsDetailsWindowTitle {
            get {
                return ResourceManager.GetString("DepsDetailsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string DepStateAvail {
            get {
                return ResourceManager.GetString("DepStateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string DepStateDown {
            get {
                return ResourceManager.GetString("DepStateDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string DepStatePaid {
            get {
                return ResourceManager.GetString("DepStatePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string DepStateUnav {
            get {
                return ResourceManager.GetString("DepStateUnav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string DepStateUnk {
            get {
                return ResourceManager.GetString("DepStateUnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route dependencies.
        /// </summary>
        public static string DepWindowTitle1 {
            get {
                return ResourceManager.GetString("DepWindowTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario dependencies.
        /// </summary>
        public static string DepWindowTitle2 {
            get {
                return ResourceManager.GetString("DepWindowTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while downloading.
        /// </summary>
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update of application....
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading packages {0}/{1}.
        /// </summary>
        public static string DownloadTitle {
            get {
                return ResourceManager.GetString("DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I..
        /// </summary>
        public static string Era1 {
            get {
                return ResourceManager.GetString("Era1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II..
        /// </summary>
        public static string Era2 {
            get {
                return ResourceManager.GetString("Era2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to III..
        /// </summary>
        public static string Era3 {
            get {
                return ResourceManager.GetString("Era3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV..
        /// </summary>
        public static string Era4 {
            get {
                return ResourceManager.GetString("Era4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V..
        /// </summary>
        public static string Era5 {
            get {
                return ResourceManager.GetString("Era5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VI..
        /// </summary>
        public static string Era6 {
            get {
                return ResourceManager.GetString("Era6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminate.
        /// </summary>
        public static string EraNon {
            get {
                return ResourceManager.GetString("EraNon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy following files!.
        /// </summary>
        public static string FailedCopyFiles {
            get {
                return ResourceManager.GetString("FailedCopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindFile for {0} returned no packages!.
        /// </summary>
        public static string FindFileFail {
            get {
                return ResourceManager.GetString("FindFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when reading gzip entry of file {0}!.
        /// </summary>
        public static string GzipEntryFail {
            get {
                return ResourceManager.GetString("GzipEntryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gzip file {0} is corrupted!.
        /// </summary>
        public static string GzipFileFail {
            get {
                return ResourceManager.GetString("GzipFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading gzip file {0}!.
        /// </summary>
        public static string GzipReadFail {
            get {
                return ResourceManager.GetString("GzipReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when trying to install package..
        /// </summary>
        public static string InstalFail {
            get {
                return ResourceManager.GetString("InstalFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing update....
        /// </summary>
        public static string InstallingUpdate {
            get {
                return ResourceManager.GetString("InstallingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #INVALID FILE NAME.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep all!.
        /// </summary>
        public static string KeepAll {
            get {
                return ResourceManager.GetString("KeepAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep local!.
        /// </summary>
        public static string KeepLocal {
            get {
                return ResourceManager.GetString("KeepLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay logged in.
        /// </summary>
        public static string LoginCheckbox {
            get {
                return ResourceManager.GetString("LoginCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login with your Railworks Download Station account..
        /// </summary>
        public static string LoginDesc {
            get {
                return ResourceManager.GetString("LoginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address....
        /// </summary>
        public static string LoginEmailHint {
            get {
                return ResourceManager.GetString("LoginEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string LoginForgot {
            get {
                return ResourceManager.GetString("LoginForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t filled all required fields..
        /// </summary>
        public static string LoginMissingField {
            get {
                return ResourceManager.GetString("LoginMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password....
        /// </summary>
        public static string LoginPasswordHint {
            get {
                return ResourceManager.GetString("LoginPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LoginPrimary {
            get {
                return ResourceManager.GetString("LoginPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginSecondary {
            get {
                return ResourceManager.GetString("LoginSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download packages.
        /// </summary>
        public static string MainDown {
            get {
                return ResourceManager.GetString("MainDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage packages.
        /// </summary>
        public static string MainManage {
            get {
                return ResourceManager.GetString("MainManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan assets....
        /// </summary>
        public static string MainRescan {
            get {
                return ResourceManager.GetString("MainRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for missing assets.
        /// </summary>
        public static string MainScan {
            get {
                return ResourceManager.GetString("MainScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Railworks folder location.
        /// </summary>
        public static string MainSelectFolder {
            get {
                return ResourceManager.GetString("MainSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer version of following package was found on server:
        ///{0}
        ///Do you want to update it?.
        /// </summary>
        public static string NewerDesc {
            get {
                return ResourceManager.GetString("NewerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, update.
        /// </summary>
        public static string NewerPrimary {
            get {
                return ResourceManager.GetString("NewerPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, keep local.
        /// </summary>
        public static string NewerSecond {
            get {
                return ResourceManager.GetString("NewerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer package found!.
        /// </summary>
        public static string NewerTitle {
            get {
                return ResourceManager.GetString("NewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to access non cached package!.
        /// </summary>
        public static string NonCached {
            get {
                return ResourceManager.GetString("NonCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some operations are still running.
        ///Do you really want to close the app?.
        /// </summary>
        public static string OperationsRunning {
            get {
                return ResourceManager.GetString("OperationsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite all!.
        /// </summary>
        public static string OverAll {
            get {
                return ResourceManager.GetString("OverAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite local!.
        /// </summary>
        public static string OverLocal {
            get {
                return ResourceManager.GetString("OverLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install package.
        /// </summary>
        public static string PackManInstall {
            get {
                return ResourceManager.GetString("PackManInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected package.
        /// </summary>
        public static string PackManRemove {
            get {
                return ResourceManager.GetString("PackManRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package manager.
        /// </summary>
        public static string PackManTitle {
            get {
                return ResourceManager.GetString("PackManTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is paid package. Paid packages cannot be downloaded through this app..
        /// </summary>
        public static string PaidPackageFail {
            get {
                return ResourceManager.GetString("PaidPackageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured during parsing following file:
        ///{0}
        ///Usually it means the file is corrupted. Please report this error message including the corrupted file..
        /// </summary>
        public static string ParseRoutePropFail {
            get {
                return ResourceManager.GetString("ParseRoutePropFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing RouteProperties.
        /// </summary>
        public static string ParseRoutePropFailTitle {
            get {
                return ResourceManager.GetString("ParseRoutePropFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing download!.
        /// </summary>
        public static string PrepareTitle {
            get {
                return ResourceManager.GetString("PrepareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal! Progress is bigger than size of all files! {0}:{1}
        ///Route: {1}.
        /// </summary>
        public static string ProgressFail {
            get {
                return ResourceManager.GetString("ProgressFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading zip file {0}!.
        /// </summary>
        public static string ReadingZipFail {
            get {
                return ResourceManager.GetString("ReadingZipFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total routes: {0}.
        /// </summary>
        public static string RoutesCountLabel {
            get {
                return ResourceManager.GetString("RoutesCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading routes failed!.
        /// </summary>
        public static string RoutesLoadFail {
            get {
                return ResourceManager.GetString("RoutesLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try finding Railworks location automatically.
        /// </summary>
        public static string SelectRWDlgAuto {
            get {
                return ResourceManager.GetString("SelectRWDlgAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string SelectRWDlgBrowse {
            get {
                return ResourceManager.GetString("SelectRWDlgBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your RailWorks (Train Simulator) installation folder..
        /// </summary>
        public static string SelectRWDlgDesc {
            get {
                return ResourceManager.GetString("SelectRWDlgDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select RailWorks folder.
        /// </summary>
        public static string SelectRWDlgTitle {
            get {
                return ResourceManager.GetString("SelectRWDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select RailWorks installation path.
        /// </summary>
        public static string SelectRWPathTitle {
            get {
                return ResourceManager.GetString("SelectRWPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when parsing bin file {0}!.
        /// </summary>
        public static string SerzCommonFail {
            get {
                return ResourceManager.GetString("SerzCommonFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to flush unreaded string id {0}, step {1} in file {2}!.
        /// </summary>
        public static string SerzFlushNStringFail {
            get {
                return ResourceManager.GetString("SerzFlushNStringFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding non loaded string id {0} at position {1}, step {2} in file {3}!.
        /// </summary>
        public static string SerzNLoadStringFail {
            get {
                return ResourceManager.GetString("SerzNLoadStringFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse existing tag on position {0}, step {1} in file {2}!.
        /// </summary>
        public static string SerzParseExTagFail {
            get {
                return ResourceManager.GetString("SerzParseExTagFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format {0} in mattrice on position {1}, step {2} in file {3}!.
        /// </summary>
        public static string SerzUnkFormatFail {
            get {
                return ResourceManager.GetString("SerzUnkFormatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown tag format {0} at position {1}, step {2}, file {3}!.
        /// </summary>
        public static string SerzUnkTagFormFail {
            get {
                return ResourceManager.GetString("SerzUnkTagFormFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data type {0} at position {1}, step {2} in file {3}!.
        /// </summary>
        public static string SerzUnkTypeFail {
            get {
                return ResourceManager.GetString("SerzUnkTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialision of SteamManager failed!.
        /// </summary>
        public static string SteamInitFail {
            get {
                return ResourceManager.GetString("SteamInitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to allow administrator privileges to update Railworks Download Station..
        /// </summary>
        public static string UpdaterAdminDesc {
            get {
                return ResourceManager.GetString("UpdaterAdminDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAC Required.
        /// </summary>
        public static string UpdaterAdminTitle {
            get {
                return ResourceManager.GetString("UpdaterAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater panic!.
        /// </summary>
        public static string UpdaterPanic {
            get {
                return ResourceManager.GetString("UpdaterPanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating packages {0}/{1}.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
