//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailworksDownloader.Localization {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RailworksDownloader.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný All available packages were already downloaded..
        /// </summary>
        public static string AllDownDesc {
            get {
                return ResourceManager.GetString("AllDownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This package is already installed..
        /// </summary>
        public static string AlreadyInstalFail {
            get {
                return ResourceManager.GetString("AlreadyInstalFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Application will be restarted.
        /// </summary>
        public static string ApplicationRestart {
            get {
                return ResourceManager.GetString("ApplicationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot download packages.
        /// </summary>
        public static string CantDownload {
            get {
                return ResourceManager.GetString("CantDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Steam DLC.
        /// </summary>
        public static string CatDLC {
            get {
                return ResourceManager.GetString("CatDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Environment.
        /// </summary>
        public static string CatEnv {
            get {
                return ResourceManager.GetString("CatEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Locomotives.
        /// </summary>
        public static string CatLoco {
            get {
                return ResourceManager.GetString("CatLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Other/Uncategorised.
        /// </summary>
        public static string CatOther {
            get {
                return ResourceManager.GetString("CatOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Railvehicle dependencies.
        /// </summary>
        public static string CatRVDep {
            get {
                return ResourceManager.GetString("CatRVDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Scenery.
        /// </summary>
        public static string CatScenery {
            get {
                return ResourceManager.GetString("CatScenery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SYSTEM PACKAGE.
        /// </summary>
        public static string CatSystem {
            get {
                return ResourceManager.GetString("CatSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Track objects.
        /// </summary>
        public static string CatTrackObj {
            get {
                return ResourceManager.GetString("CatTrackObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Wagons.
        /// </summary>
        public static string CatWag {
            get {
                return ResourceManager.GetString("CatWag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Checking installed DLCs.
        /// </summary>
        public static string CheckingDLC {
            get {
                return ResourceManager.GetString("CheckingDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Following package seems to be controlled by DLS but not installed through this app:.
        /// </summary>
        public static string ConflictFileDesc1 {
            get {
                return ResourceManager.GetString("ConflictFileDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please decide how to continue!.
        /// </summary>
        public static string ConflictFileDesc2 {
            get {
                return ResourceManager.GetString("ConflictFileDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Conflict file found!.
        /// </summary>
        public static string ConflictFileTitle {
            get {
                return ResourceManager.GetString("ConflictFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Non specified.
        /// </summary>
        public static string CountryNon {
            get {
                return ResourceManager.GetString("CountryNon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error while counting size of file {0}!.
        /// </summary>
        public static string CountSizeFail {
            get {
                return ResourceManager.GetString("CountSizeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error when crawling route &quot;{0}&quot;!.
        /// </summary>
        public static string CrawlingRouteFail {
            get {
                return ResourceManager.GetString("CrawlingRouteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Critical error!.
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Files used from package {0} in route {1}:.
        /// </summary>
        public static string DepsDetailsWindowTitle {
            get {
                return ResourceManager.GetString("DepsDetailsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Available.
        /// </summary>
        public static string DepStateAvail {
            get {
                return ResourceManager.GetString("DepStateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Downloaded.
        /// </summary>
        public static string DepStateDown {
            get {
                return ResourceManager.GetString("DepStateDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Paid.
        /// </summary>
        public static string DepStatePaid {
            get {
                return ResourceManager.GetString("DepStatePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unavailable.
        /// </summary>
        public static string DepStateUnav {
            get {
                return ResourceManager.GetString("DepStateUnav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unknown.
        /// </summary>
        public static string DepStateUnk {
            get {
                return ResourceManager.GetString("DepStateUnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Route dependencies.
        /// </summary>
        public static string DepWindowTitle1 {
            get {
                return ResourceManager.GetString("DepWindowTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Scenario dependencies.
        /// </summary>
        public static string DepWindowTitle2 {
            get {
                return ResourceManager.GetString("DepWindowTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error occured while downloading.
        /// </summary>
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Downloading update of application....
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Downloading packages {0}/{1}.
        /// </summary>
        public static string DownloadTitle {
            get {
                return ResourceManager.GetString("DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný I..
        /// </summary>
        public static string Era1 {
            get {
                return ResourceManager.GetString("Era1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný II..
        /// </summary>
        public static string Era2 {
            get {
                return ResourceManager.GetString("Era2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný III..
        /// </summary>
        public static string Era3 {
            get {
                return ResourceManager.GetString("Era3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný IV..
        /// </summary>
        public static string Era4 {
            get {
                return ResourceManager.GetString("Era4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný V..
        /// </summary>
        public static string Era5 {
            get {
                return ResourceManager.GetString("Era5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný VI..
        /// </summary>
        public static string Era6 {
            get {
                return ResourceManager.GetString("Era6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Indeterminate.
        /// </summary>
        public static string EraNon {
            get {
                return ResourceManager.GetString("EraNon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to copy following files!.
        /// </summary>
        public static string FailedCopyFiles {
            get {
                return ResourceManager.GetString("FailedCopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FindFile for {0} returned no packages!.
        /// </summary>
        public static string FindFileFail {
            get {
                return ResourceManager.GetString("FindFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error when reading gzip entry of file {0}!.
        /// </summary>
        public static string GzipEntryFail {
            get {
                return ResourceManager.GetString("GzipEntryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Gzip file {0} is corrupted!.
        /// </summary>
        public static string GzipFileFail {
            get {
                return ResourceManager.GetString("GzipFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error while reading gzip file {0}!.
        /// </summary>
        public static string GzipReadFail {
            get {
                return ResourceManager.GetString("GzipReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný An error occured when trying to install package..
        /// </summary>
        public static string InstalFail {
            get {
                return ResourceManager.GetString("InstalFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Installing....
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Installing update....
        /// </summary>
        public static string InstallingUpdate {
            get {
                return ResourceManager.GetString("InstallingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný #INVALID FILE NAME.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Keep all!.
        /// </summary>
        public static string KeepAll {
            get {
                return ResourceManager.GetString("KeepAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Keep local!.
        /// </summary>
        public static string KeepLocal {
            get {
                return ResourceManager.GetString("KeepLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Stay logged in.
        /// </summary>
        public static string LoginCheckbox {
            get {
                return ResourceManager.GetString("LoginCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please login with your Railworks Download Station account..
        /// </summary>
        public static string LoginDesc {
            get {
                return ResourceManager.GetString("LoginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný E-mail address....
        /// </summary>
        public static string LoginEmailHint {
            get {
                return ResourceManager.GetString("LoginEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Forgot password.
        /// </summary>
        public static string LoginForgot {
            get {
                return ResourceManager.GetString("LoginForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You haven&apos;t filled all required fields..
        /// </summary>
        public static string LoginMissingField {
            get {
                return ResourceManager.GetString("LoginMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Password....
        /// </summary>
        public static string LoginPasswordHint {
            get {
                return ResourceManager.GetString("LoginPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel.
        /// </summary>
        public static string LoginPrimary {
            get {
                return ResourceManager.GetString("LoginPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Login.
        /// </summary>
        public static string LoginSecondary {
            get {
                return ResourceManager.GetString("LoginSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Download packages.
        /// </summary>
        public static string MainDown {
            get {
                return ResourceManager.GetString("MainDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Manage packages.
        /// </summary>
        public static string MainManage {
            get {
                return ResourceManager.GetString("MainManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rescan assets....
        /// </summary>
        public static string MainRescan {
            get {
                return ResourceManager.GetString("MainRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Scan for missing assets.
        /// </summary>
        public static string MainScan {
            get {
                return ResourceManager.GetString("MainScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select Railworks folder location.
        /// </summary>
        public static string MainSelectFolder {
            get {
                return ResourceManager.GetString("MainSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Newer version of following package was found on server:
        ///{0}
        ///Do you want to update it?.
        /// </summary>
        public static string NewerDesc {
            get {
                return ResourceManager.GetString("NewerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Yes, update.
        /// </summary>
        public static string NewerPrimary {
            get {
                return ResourceManager.GetString("NewerPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No, keep local.
        /// </summary>
        public static string NewerSecond {
            get {
                return ResourceManager.GetString("NewerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Newer package found!.
        /// </summary>
        public static string NewerTitle {
            get {
                return ResourceManager.GetString("NewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Attempted to access non cached package!.
        /// </summary>
        public static string NonCached {
            get {
                return ResourceManager.GetString("NonCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Some operations are still running.
        ///Do you really want to close the app?.
        /// </summary>
        public static string OperationsRunning {
            get {
                return ResourceManager.GetString("OperationsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Overwrite all!.
        /// </summary>
        public static string OverAll {
            get {
                return ResourceManager.GetString("OverAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Overwrite local!.
        /// </summary>
        public static string OverLocal {
            get {
                return ResourceManager.GetString("OverLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Install package.
        /// </summary>
        public static string PackManInstall {
            get {
                return ResourceManager.GetString("PackManInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Remove selected package.
        /// </summary>
        public static string PackManRemove {
            get {
                return ResourceManager.GetString("PackManRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Package manager.
        /// </summary>
        public static string PackManTitle {
            get {
                return ResourceManager.GetString("PackManTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This is paid package. Paid packages cannot be downloaded through this app..
        /// </summary>
        public static string PaidPackageFail {
            get {
                return ResourceManager.GetString("PaidPackageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný An unexpected error occured during parsing following file:
        ///{0}
        ///Usually it means the file is corrupted. Please report this error message including the corrupted file..
        /// </summary>
        public static string ParseRoutePropFail {
            get {
                return ResourceManager.GetString("ParseRoutePropFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error parsing RouteProperties.
        /// </summary>
        public static string ParseRoutePropFailTitle {
            get {
                return ResourceManager.GetString("ParseRoutePropFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Preparing download!.
        /// </summary>
        public static string PrepareTitle {
            get {
                return ResourceManager.GetString("PrepareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Fatal! Progress is bigger than size of all files! {0}:{1}
        ///Route: {1}.
        /// </summary>
        public static string ProgressFail {
            get {
                return ResourceManager.GetString("ProgressFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error reading zip file {0}!.
        /// </summary>
        public static string ReadingZipFail {
            get {
                return ResourceManager.GetString("ReadingZipFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Loading routes failed!.
        /// </summary>
        public static string RoutesLoadFail {
            get {
                return ResourceManager.GetString("RoutesLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Try finding Railworks location automatically.
        /// </summary>
        public static string SelectRWDlgAuto {
            get {
                return ResourceManager.GetString("SelectRWDlgAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Browse.
        /// </summary>
        public static string SelectRWDlgBrowse {
            get {
                return ResourceManager.GetString("SelectRWDlgBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please select your RailWorks (Train Simulator) installation folder..
        /// </summary>
        public static string SelectRWDlgDesc {
            get {
                return ResourceManager.GetString("SelectRWDlgDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select RailWorks folder.
        /// </summary>
        public static string SelectRWDlgTitle {
            get {
                return ResourceManager.GetString("SelectRWDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select RailWorks installation path.
        /// </summary>
        public static string SelectRWPathTitle {
            get {
                return ResourceManager.GetString("SelectRWPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error when parsing bin file {0}!.
        /// </summary>
        public static string SerzCommonFail {
            get {
                return ResourceManager.GetString("SerzCommonFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Attempted to flush unreaded string id {0}, step {1} in file {2}!.
        /// </summary>
        public static string SerzFlushNStringFail {
            get {
                return ResourceManager.GetString("SerzFlushNStringFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Adding non loaded string id {0} at position {1}, step {2} in file {3}!.
        /// </summary>
        public static string SerzNLoadStringFail {
            get {
                return ResourceManager.GetString("SerzNLoadStringFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unable to parse existing tag on position {0}, step {1} in file {2}!.
        /// </summary>
        public static string SerzParseExTagFail {
            get {
                return ResourceManager.GetString("SerzParseExTagFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unknown format {0} in mattrice on position {1}, step {2} in file {3}!.
        /// </summary>
        public static string SerzUnkFormatFail {
            get {
                return ResourceManager.GetString("SerzUnkFormatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unknown tag format {0} at position {1}, step {2}, file {3}!.
        /// </summary>
        public static string SerzUnkTagFormFail {
            get {
                return ResourceManager.GetString("SerzUnkTagFormFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unknown data type {0} at position {1}, step {2} in file {3}!.
        /// </summary>
        public static string SerzUnkTypeFail {
            get {
                return ResourceManager.GetString("SerzUnkTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Initialision of SteamManager failed!.
        /// </summary>
        public static string SteamInitFail {
            get {
                return ResourceManager.GetString("SteamInitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unknown error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You need to allow administrator privileges to update Railworks Download Station..
        /// </summary>
        public static string UpdaterAdminDesc {
            get {
                return ResourceManager.GetString("UpdaterAdminDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UAC Required.
        /// </summary>
        public static string UpdaterAdminTitle {
            get {
                return ResourceManager.GetString("UpdaterAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Updater panic!.
        /// </summary>
        public static string UpdaterPanic {
            get {
                return ResourceManager.GetString("UpdaterPanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Updating packages {0}/{1}.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
