//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailworksDownloader {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLqueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLqueries() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RailworksDownloader.SQLqueries", typeof(SQLqueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ALTER TABLE {0} ADD COLUMN {1} {2};.
        /// </summary>
        internal static string AddColumn {
            get {
                return ResourceManager.GetString("AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DELETE FROM dependencies;.
        /// </summary>
        internal static string DeleteAllDeps {
            get {
                return ResourceManager.GetString("DeleteAllDeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DELETE FROM installed_files WHERE file_name = @file_name;.
        /// </summary>
        internal static string DeleteInstalledFilesWhere {
            get {
                return ResourceManager.GetString("DeleteInstalledFilesWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DELETE FROM file_list WHERE package_id = @id;.
        /// </summary>
        internal static string DeletePkgFilesWhere {
            get {
                return ResourceManager.GetString("DeletePkgFilesWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DELETE FROM package_list WHERE id = @id;.
        /// </summary>
        internal static string DeletePkgWhere {
            get {
                return ResourceManager.GetString("DeletePkgWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný INSERT INTO checksums (folder, chcksum, last_write) VALUES (@folder,@chcksum,@last_write) ON CONFLICT(folder) DO UPDATE SET folder = @folder, chcksum = @chcksum, last_write = @last_write;.
        /// </summary>
        internal static string InsertChckSum {
            get {
                return ResourceManager.GetString("InsertChckSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný INSERT INTO dependencies (path, isScenario) VALUES (@path,@isScenario);.
        /// </summary>
        internal static string InsertDeps {
            get {
                return ResourceManager.GetString("InsertDeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný INSERT INTO installed_files (package_id, file_name) VALUES (@package_id,@file_name);.
        /// </summary>
        internal static string InsertInstalledFiles {
            get {
                return ResourceManager.GetString("InsertInstalledFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný INSERT INTO package_list (
        ///    id,
        ///    file_name,
        ///    display_name,
        ///    category,
        ///    era,
        ///    country,
        ///    version,
        ///    owner,
        ///    datetime,
        ///    description,
        ///    target_path
        ///) VALUES (
        ///    @id,
        ///    @file_name,
        ///    @display_name,
        ///    @category,
        ///    @era,
        ///    @country,
        ///    @version,
        ///    @owner,
        ///    @datetime,
        ///    @description,
        ///    @target_path
        ///) ON CONFLICT(id) DO UPDATE SET 
        ///file_name = @file_name,
        ///display_name = @display_name,
        ///category = @category,
        ///era = @era,
        ///country = @countr [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string InsertPkg {
            get {
                return ResourceManager.GetString("InsertPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný INSERT INTO file_list (package_id, file_name) VALUES (@package_id,@file_name);.
        /// </summary>
        internal static string InsertPkgFiles {
            get {
                return ResourceManager.GetString("InsertPkgFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PRAGMA table_info({0});.
        /// </summary>
        internal static string ListTableRows {
            get {
                return ResourceManager.GetString("ListTableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SELECT * FROM checksums;.
        /// </summary>
        internal static string SelectAllChckSums {
            get {
                return ResourceManager.GetString("SelectAllChckSums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SELECT * FROM dependencies;.
        /// </summary>
        internal static string SelectAllDeps {
            get {
                return ResourceManager.GetString("SelectAllDeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SELECT * FROM package_list;.
        /// </summary>
        internal static string SelectAllPkgs {
            get {
                return ResourceManager.GetString("SelectAllPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SELECT * FROM file_list WHERE package_id = @package_id;.
        /// </summary>
        internal static string SelectFilesWhere {
            get {
                return ResourceManager.GetString("SelectFilesWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SELECT * FROM installed_files WHERE package_id = @package_id;.
        /// </summary>
        internal static string SelectInstalledFilesWhere {
            get {
                return ResourceManager.GetString("SelectInstalledFilesWhere", resourceCulture);
            }
        }
    }
}
